// <auto-generated />
using System;
using KuShop.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KuShop.Migrations
{
    [DbContext(typeof(KuShopContext))]
    partial class KuShopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KuShop.Models.BuyDtl", b =>
                {
                    b.Property<string>("BuyId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("BuyID");

                    b.Property<string>("PdId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PdID");

                    b.Property<double?>("BdtlMoney")
                        .HasColumnType("float")
                        .HasColumnName("BDtlMoney");

                    b.Property<double?>("BdtlPrice")
                        .HasColumnType("float")
                        .HasColumnName("BDtlPrice");

                    b.Property<double?>("BdtlQty")
                        .HasColumnType("float")
                        .HasColumnName("BDtlQty");

                    b.HasKey("BuyId", "PdId")
                        .HasName("PK_BuyDtl");

                    b.ToTable("BuyDtls");
                });

            modelBuilder.Entity("KuShop.Models.Buying", b =>
                {
                    b.Property<string>("BuyId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("BuyDate")
                        .HasColumnType("date");

                    b.Property<string>("BuyDocId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("BuyDocID");

                    b.Property<double?>("BuyMoney")
                        .HasColumnType("float");

                    b.Property<double?>("BuyQty")
                        .HasColumnType("float");

                    b.Property<string>("BuyRemark")
                        .HasColumnType("text");

                    b.Property<string>("Saleman")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StfId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("StfID");

                    b.Property<string>("PubId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SupID");

                    b.HasKey("BuyId");

                    b.ToTable("Buying", (string)null);
                });

            modelBuilder.Entity("KuShop.Models.Cart", b =>
                {
                    b.Property<string>("CartId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CartID");

                    b.Property<string>("CartCf")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("nchar(1)")
                        .HasDefaultValue("N")
                        .HasColumnName("CartCF")
                        .IsFixedLength();

                    b.Property<DateOnly?>("CartDate")
                        .HasColumnType("date");

                    b.Property<double?>("CartMoney")
                        .HasColumnType("float");

                    b.Property<string>("CartPay")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("nchar(1)")
                        .HasDefaultValue("N")
                        .IsFixedLength();

                    b.Property<double?>("CartQty")
                        .HasColumnType("float");

                    b.Property<string>("CartSend")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("nchar(1)")
                        .HasDefaultValue("N")
                        .IsFixedLength();

                    b.Property<string>("CartVoid")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("nchar(1)")
                        .HasDefaultValue("N")
                        .IsFixedLength();

                    b.Property<string>("CusId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CusID");

                    b.HasKey("CartId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("KuShop.Models.CartDtl", b =>
                {
                    b.Property<string>("CartId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CartID");

                    b.Property<string>("PdId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PdID");

                    b.Property<double?>("CdtlMoney")
                        .HasColumnType("float")
                        .HasColumnName("CDtlMoney");

                    b.Property<double?>("CdtlPrice")
                        .HasColumnType("float")
                        .HasColumnName("CDtlPrice");

                    b.Property<double?>("CdtlQty")
                        .HasColumnType("float")
                        .HasColumnName("CDtlQty");

                    b.HasKey("CartId", "PdId")
                        .HasName("PK_CartDtl");

                    b.ToTable("CartDtls");
                });

            modelBuilder.Entity("KuShop.Models.Customer", b =>
                {
                    b.Property<string>("CusId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CusID");

                    b.Property<string>("CusAdd")
                        .HasColumnType("text");

                    b.Property<string>("CusEmail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CusLogin")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CusName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CusPass")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("LastLogin")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("CusId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("KuShop.Models.Developer", b =>
                {
                    b.Property<byte>("DevId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasColumnName("BrandID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("DevId"));

                    b.Property<string>("DevName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DevId")
                        .HasName("PK_ProductBrands");

                    b.ToTable("Devs");
                });

            modelBuilder.Entity("KuShop.Models.Duty", b =>
                {
                    b.Property<string>("DutyId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DutyID");

                    b.Property<string>("DutyName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DutyId");

                    b.ToTable("Duty", (string)null);
                });

            modelBuilder.Entity("KuShop.Models.Product", b =>
                {
                    b.Property<string>("PdId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PdID");

                    b.Property<byte?>("DevId")
                        .HasColumnType("tinyint")
                        .HasColumnName("BrandID");

                    b.Property<double?>("PdCost")
                        .HasColumnType("float");

                    b.Property<DateOnly?>("PdLastBuy")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("PdLastSale")
                        .HasColumnType("date");

                    b.Property<string>("PdName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("PdPrice")
                        .HasColumnType("float");

                    b.Property<double?>("PdStk")
                        .HasColumnType("float");

                    b.Property<byte?>("GenreId")
                        .HasColumnType("tinyint")
                        .HasColumnName("PdtID");

                    b.HasKey("PdId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("KuShop.Models.Genre", b =>
                {
                    b.Property<byte>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasColumnName("PdtID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("GenreId"));

                    b.Property<string>("GenreName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("GenreId");

                    b.ToTable("ProductTypes");
                });

            modelBuilder.Entity("KuShop.Models.Staff", b =>
                {
                    b.Property<string>("StfId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("StfID");

                    b.Property<string>("DutyId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DutyID");

                    b.Property<DateOnly?>("QuitDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("StfName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StfPass")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StfId")
                        .HasName("PK_Employees");

                    b.ToTable("Staffs");
                });

            modelBuilder.Entity("KuShop.Models.Publisher", b =>
                {
                    b.Property<string>("PubAdd")
                        .HasColumnType("text");

                    b.Property<string>("PubContact")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PubEmail")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PubId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SupID");

                    b.Property<string>("PubName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PubRemark")
                        .HasColumnType("text");

                    b.Property<string>("PubTel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("KuShop.Models.Work", b =>
                {
                    b.Property<string>("StfId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("WorkDate")
                        .HasColumnType("date");

                    b.Property<string>("WorkIn")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("WorkOut")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.ToTable("Works");
                });
#pragma warning restore 612, 618
        }
    }
}
